# Generated by Django 4.1.1 on 2022-10-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
