# Generated by Django 4.1.1 on 2022-10-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0010_alter_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
