# Generated by Django 4.1.1 on 2022-10-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0011_lead_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_week_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='this_week_orders',
            field=models.IntegerField(default=0),
        ),
    ]
