# Generated by Django 4.1.1 on 2022-11-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0012_product_last_week_orders_product_this_week_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='color_en',
        ),
        migrations.AddField(
            model_name='color',
            name='color_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='color_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
