# Generated by Django 4.0.6 on 2022-09-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='tag_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tag_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tag_uz',
        ),
    ]
